<?php if (Mage::getStoreConfig('instagram/general/jquery')) : ?>
    <script src="<?php echo $this->getSkinUrl('magazento_instagram/js/jquery-1.7.1.min.js') ?>" type="text/javascript"></script>
<?php endif; ?>
<script src="<?php echo $this->getSkinUrl('magazento_instagram/js/masonry.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('magazento_instagram/js/jquery.jscrollpane.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('magazento_instagram/js/jquery.mousewheel.js') ?>" type="text/javascript"></script>
<script type="text/javascript">
    jQmagazento = jQuery.noConflict();
</script>